name: Build Common Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  set-version:
    uses: NivagL/Common.Tools/.github/workflows/BuildVersion.yml@main
    with:
      major: 1
      minor: 0

  build-nuget-package:
    needs: set-version
    uses: NivagL/Common.Tools/.github/workflows/BuildNuget.yml@main
    with:
      project: 'matoa.model'
      version: ${{ needs.set-version.outputs['build-version'] }}
    secrets: inherit

  build-npm-package:
    needs: build-nuget-package
    uses: NivagL/Common.Tools/.github/workflows/BuildNpm.yml@main
    with:
      project: 'matoa.model'
      version: ${{ needs.set-version.outputs['build-version'] }}
    secrets: inherit
