name: Build and Publish NuGet Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Restore .NET tools
      run: dotnet tool restore
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ inputs.version }}
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Push to GitHub Packages
      run: dotnet nuget push ./matoa.model/bin/Release/*.nupkg --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
